name: CytoExploreR Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: QEMU
      uses: docker/setup-qemu-action@v1
    - name: Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker Hub Login
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: CytoExploreR Docker Build & Push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: dhammill/cytoexplorer-devel:latest
        github-token: ${{ secrets.GITHUB_TOKEN }}
